In [1]:
!pip3 install torch torchvision

     ------------------------------------ 162.6/162.6 MB 924.0 kB/s eta 0:00:00
     ---------------------------------------- 1.1/1.1 MB 3.1 MB/s eta 0:00:00
     -------------------------------------- 62.8/62.8 kB 674.1 kB/s eta 0:00:00
     -------------------------------------- 140.6/140.6 kB 1.7 MB/s eta 0:00:00
     -------------------------------------- 94.0/94.0 kB 768.5 kB/s eta 0:00:00
     ------------------------------------ 155.3/155.3 kB 488.3 kB/s eta 0:00:00


In [2]:
import torch
from IPython import display
import numpy as np
import random

Создайте случайный FloatTensor размера 3x4x5 <br>
Выведите его форму (shape) <br>
Приведите его к форме 6х10 <br>
Создайте случайный IntTensor размера 10 <br>
Умножьте созданный FloatTensor на созданный IntTensor поэлементно <br>
Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти <br>
Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)<br>
Создайте единичный тензор размера 5x6 <br>
Переведите его в формат numpy<br>

In [3]:
# 1. Создайте случайный FloatTensor размера 3x4x5
tensor = torch.rand(3, 4, 5)
tensor

tensor([[[0.3233, 0.6543, 0.9759, 0.3927, 0.7545],
         [0.2977, 0.9289, 0.9990, 0.7312, 0.6365],
         [0.9737, 0.1083, 0.4678, 0.0795, 0.6540],
         [0.8066, 0.0519, 0.3033, 0.0907, 0.3162]],

        [[0.3815, 0.4620, 0.8404, 0.7142, 0.1037],
         [0.6060, 0.8913, 0.3602, 0.4300, 0.0888],
         [0.8434, 0.9039, 0.4299, 0.5145, 0.2847],
         [0.8701, 0.4897, 0.5380, 0.0949, 0.2961]],

        [[0.0559, 0.0340, 0.3767, 0.9185, 0.0797],
         [0.1480, 0.9690, 0.2963, 0.2277, 0.2664],
         [0.6873, 0.9700, 0.0521, 0.6368, 0.4838],
         [0.6981, 0.2929, 0.6486, 0.3327, 0.5766]]])

In [4]:
# 2. Выведите его форму (shape)
tensor.shape

torch.Size([3, 4, 5])

In [5]:
# 3. Приведите его к форме 6х10
tensor_reshape = tensor.reshape(6, 10)
tensor_reshape

tensor([[0.3233, 0.6543, 0.9759, 0.3927, 0.7545, 0.2977, 0.9289, 0.9990, 0.7312,
         0.6365],
        [0.9737, 0.1083, 0.4678, 0.0795, 0.6540, 0.8066, 0.0519, 0.3033, 0.0907,
         0.3162],
        [0.3815, 0.4620, 0.8404, 0.7142, 0.1037, 0.6060, 0.8913, 0.3602, 0.4300,
         0.0888],
        [0.8434, 0.9039, 0.4299, 0.5145, 0.2847, 0.8701, 0.4897, 0.5380, 0.0949,
         0.2961],
        [0.0559, 0.0340, 0.3767, 0.9185, 0.0797, 0.1480, 0.9690, 0.2963, 0.2277,
         0.2664],
        [0.6873, 0.9700, 0.0521, 0.6368, 0.4838, 0.6981, 0.2929, 0.6486, 0.3327,
         0.5766]])

In [6]:
# 4. Создайте случайный IntTensor размера 10
int_tensor = torch.IntTensor(10)
int_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

In [7]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
mult_tensor = tensor_reshape * int_tensor
mult_tensor

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
torch.mm(mult_tensor, torch.transpose(mult_tensor, 0 , 1))

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [9]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
args = torch.tensor([1., 1., 1.])
x = torch.tensor([1., 1., 1.], requires_grad=True)
z = torch.tensor([0.5, 0.5, 0.5], requires_grad=True)
t = torch.tensor([2., 2., 2.], requires_grad=True)

y = x ** 3 + z - 75 * t

y.backward(gradient=args)
x.grad, z.grad, t.grad

(tensor([3., 3., 3.]), tensor([1., 1., 1.]), tensor([-75., -75., -75.]))

In [10]:
# 8. Создайте единичный тензор размера 5x6
ones_tensor = torch.ones((5, 6))
ones_tensor

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
# 9. Переведите его в формат numpy
np_ones_tensor = ones_tensor.numpy()
np_ones_tensor

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)